import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

function getAlertReasons(report: any) {
  const reasons: string[] = [];

  if (report.severity === "Critical") reasons.push("Critical Incident");
  if (report.emergency_services) reasons.push("Emergency Services Involved");
  if (report.follow_up_required) reasons.push("Follow-up Required");

  return reasons;
}

export async function POST(request: Request) {
  try {
    const report = await request.json();

    const alertReasons = getAlertReasons(report);

    if (alertReasons.length === 0) {
      return Response.json({
        skipped: true,
        message: "No alert conditions met.",
      });
    }

    const recipient = process.env.ALERT_EMAIL_TO;

    if (!recipient) {
      return Response.json(
        { error: "ALERT_EMAIL_TO is not configured." },
        { status: 500 }
      );
    }

    const dashboardUrl =
      process.env.NEXT_PUBLIC_SITE_URL ||
      "https://smsw-security-log.vercel.app";

    const subject = `SMSW Incident Alert - ${alertReasons.join(" / ")} - ${
      report.site_location || "Unknown Site"
    }`;

    const html = `
      <div style="font-family: Arial, sans-serif; color: #111827; line-height: 1.5;">
        <h2 style="color: #991b1b;">SMSW Incident Alert</h2>

        <p><strong>Alert Reason:</strong> ${alertReasons.join(", ")}</p>

        <hr />

        <p><strong>Log Number:</strong> ${report.log_number || "N/A"}</p>
        <p><strong>Site:</strong> ${report.site_location || "N/A"}</p>
        <p><strong>Site ID:</strong> ${report.site_id || "N/A"}</p>
        <p><strong>Officer:</strong> ${report.officer_name || "N/A"}</p>
        <p><strong>Officer ID:</strong> ${report.officer_id || "N/A"}</p>
        <p><strong>Duty Role:</strong> ${report.duty_role || "N/A"}</p>

        <hr />

        <p><strong>Severity:</strong> ${report.severity || "N/A"}</p>
        <p><strong>Incident Date:</strong> ${report.incident_date || "N/A"}</p>
        <p><strong>Incident Time:</strong> ${report.incident_time || "N/A"}</p>
        <p><strong>Exact Location:</strong> ${report.exact_location || "N/A"}</p>
        <p><strong>Persons Involved:</strong> ${
          report.persons_involved || "N/A"
        }</p>

        <hr />

        <p><strong>Emergency Services:</strong> ${
          report.emergency_services ? "Yes" : "No"
        }</p>
        <p><strong>Emergency Service Type:</strong> ${
          report.emergency_service_type || "N/A"
        }</p>
        <p><strong>CAD / Log Number:</strong> ${
          report.emergency_service_log_number || "N/A"
        }</p>
        <p><strong>Supervisor Notified:</strong> ${
          report.supervisor_notified ? "Yes" : "No"
        }</p>
        <p><strong>Client Notified:</strong> ${
          report.client_notified ? "Yes" : "No"
        }</p>
        <p><strong>Follow-up Required:</strong> ${
          report.follow_up_required ? "Yes" : "No"
        }</p>

        <hr />

        <p><strong>Description:</strong></p>
        <p style="white-space: pre-wrap; background: #f9fafb; padding: 12px; border: 1px solid #e5e7eb;">
          ${report.description || "No description provided"}
        </p>

        <p><strong>Action Taken:</strong></p>
        <p style="white-space: pre-wrap; background: #f9fafb; padding: 12px; border: 1px solid #e5e7eb;">
          ${report.action_taken || "No action recorded"}
        </p>

        <hr />

        <p>
          <a href="${dashboardUrl}/dashboard" style="display: inline-block; background: #111827; color: #ffffff; padding: 10px 14px; text-decoration: none; border-radius: 6px;">
            Open SMSW Dashboard
          </a>
        </p>

        <p style="font-size: 12px; color: #6b7280;">
          This automated alert was generated by the SMSW Incident Reporting Platform.
        </p>
      </div>
    `;

    const { data, error } = await resend.emails.send({
      from: "SMSW Alerts <onboarding@resend.dev>",
      to: recipient,
      subject,
      html,
    });

    if (error) {
      console.error("Resend error:", error);
      return Response.json({ error }, { status: 500 });
    }

    return Response.json({ success: true, data });
  } catch (error) {
    console.error("Email alert error:", error);

    return Response.json(
      { error: "Could not send incident alert." },
      { status: 500 }
    );
  }
}